### ISSUE TITLE
If the tag is not registered, sql error.

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Plugins/autotags#10]
If the tag is not registered, sql error.

/admin/plugins/autotags/index.php?mode=edit&tag=XXXXX
---> SQL error
E_USER_ERROR(256) - 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 @ /.../private/diving/system/databases/mysqli.class.php line 468

Request:
If the tag is not registered, then create page like Static Page plugin.

**Comment by eSilverStrike** [comment]
Fixed. If editor receives invalid id then editor will be displayed so admin can create a new autotag.
