### ISSUE TITLE
Autotags error

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Plugins/autotags#7]
https://github.com/ivywe/geeklog-ivywe/commit/7d928e9a2a165ac814f968b5b8f1098b7679979e
Add 'list_all_title' => 'Autotag Manager'

**Comment by ivywe** [comment]
https://github.com/ivywe/geeklog-ivywe/commit/400dc2b0e0d0afdde8b613d99b8a69add0446a59
Change admin path

**Comment by ivywe** [comment]
https://github.com/ivywe/geeklog-ivywe/commit/18d73c53ad25028c6cd39fd0cd8ceda4fc39888a
Add security
Hide admin path from public pages

**Comment by eSilverStrike** [comment]
Hi Ivy, Your autotag commits looks like they are not needed. "list_all_title" is not used anywhere in the current code. Instead we use $LANG_AUTO['autotagsmanager'].

Also  the last 2 comments listed seem to be for the themeeditor plugin and not the Autotag plugin.

**Comment by ivywe** [comment]
> Also the last 2 comments listed seem to be for the themeeditor plugin and not the Autotag plugin.

Sorry, sure.
