### ISSUE TITLE
Requires Close Tag Autotags are error when using in template.

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Plugins/autotags#9]
template:
{!!autotag XXX:... !!}....{!!autotag /XXX !!}

then error message appear.

"Error Autotag not correct format"

```
$LANG32 
    32 => '<p><b>Error Autotag not correct format</b></p>',
```

**Comment by eSilverStrike** [comment]
Just tested and this works fine. 

You are just using the wrong format. You only need {!!autotag ... !!} Try:

{!!autotag html:em]some text here[/html !!}

or

{!!autotag XXX:...]....[/XXX !!}
